os: linux
dist: bionic

language: php

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mysql

jobs:
  include:
    - php: 8.0
      env: WP_VERSION=latest
      name: PHPUnit tests (PHP 8.0, latest WP)
    - php: 7.4
      env: WP_VERSION=latest
      name: PHPUnit tests (PHP 7.4, latest WP)
    - php: 7.3
      env: WP_VERSION=latest
      name: PHPUnit tests (PHP 7.3, latest WP)
    - php: 7.2
      env: WP_VERSION=4.6
      name: PHPUnit tests (PHP 7.2, WP 4.6)
    - php: 7.2
      env: WP_VERSION=5.0
      name: PHPUnit tests (PHP 7.2, WP 5.0)
    - php: 7.2
      env: WP_VERSION=latest
      name: PHPUnit tests (PHP 7.2, latest WP)
    - php: 5.6
      env: WP_VERSION=trunk
      name: PHPUnit tests (PHP 7.2, WP trunk)
    - php: 7.2
      env: WP_TRAVISCI=phpcs
      dist: precise
      name: PHP CodeSniffer

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      composer global require "phpunit/phpunit=4.8.*|5.7.*"
      if [[ "$(phpenv version-name)" != "5.6" ]] && [[ "$(phpenv version-name)" != "7.0" ]] ; then
        composer install --ignore-platform-reqs
        vendor/bin/php-scoper add-prefix --force && cd build && composer dump-autoload && cd ..
      else
        composer dump-autoload
      fi
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer install --ignore-platform-reqs
      vendor/bin/phpcs --config-set ignore_warnings_on_exit 1
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      phpunit
      WP_MULTISITE=1 phpunit
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      vendor/bin/phpcs
    fi
